### ISSUE TITLE
Demo Checklist

### ISSUE THREAD

**Issue by moziauddin** [ess-acppo/ag-bie-solr#3]
### Pick a dataset in NAQS - 2m

- Algae is the smallest dataset with many issues (more later)
- Picking algae to show conflicts and resolution
- Smaller datasets are: algae, fungi and lichen
- Fungi data issues. So, pick algae

**Expectations:**  1m

1. Quick changes for Demo
1. Lots of changes, so pace might be a bit high
1. Hackish way to change taxa at NAQS and CoL
1. Over-simplified set compared to prod
1. NSL is too complicated to show in 20 mins, so only key features are covered
2. NSL editor will be used only by a few editors. Most users and systems will interface with TRS search

#### Single Source: 13m

1. [x] Go over the dataset - flyby view (maybe use colors to aid) **3m**
1. [x] Review Initial Data. Same taxa with different ids
1. [x] Fix NAQS data e.g. Kingdom (Eukaryota)  **8m**
    - [x] Rename kingdom Eukaryota instead of `Algae` 
    - [x] Move `Ulvophyceae` to right place
    - [x] `Aegagropila` and `Aegagropila Kützing, 1843` - Has author
    - [x] `Aegagropila linnaei` and `Aegagropila linnaei Kützing, 1843` - Has author
    - [x] `Cephaleuros` and `Cephaleuros` - Same text name **stay separate** why?
1. [x] Show Taxonomy Report on dev1-ag-bie (maybe when the taxa is combined) **2m**
1. [x] What happens to an identifier if it has changed at source by GBIF, CoL or NSL (NSL is special case)

#### Two Sources: 6m

2. [x] Emter *NSL*. Merge two seperate taxonomies from top. Review data
    - [x] Where is [Rhodophyta](https://dev1-ag-bie.oztaxa.com/species/107179#classification) 
    - [Bangiales](https://dev1-ag-bie.oztaxa.com/species/https://test-id.biodiversity.org.au/taxon/algae/20212984#)
    - [Bangiaceae](https://dev1-ag-bie.oztaxa.com/species/https://test-id.biodiversity.org.au/taxon/algae/20212985#names)
1. [x] Show how same names with different text are merged.
1. [x] Change Source `priority` for NAQS and have a look at taxa
    - [Rhodophyta](https://dev1-ag-bie.oztaxa.com/species/107179#classification) - Moves from sub-king to King
1. [x] Searching Synonyms from NSL in TRS (Difference from NAQS)
    - Mention `Aegagropila membranacea` - Synonyms imported
    - [Achnanthes brevipes C.Agardh :: Achnanthes adnata Bory](https://dev1-ag-bie.oztaxa.com/species/https://test-id.biodiversity.org.au/taxon/algae/20215645#names)
    - [Achnanthes coarctata & Achnanthes coarctatum](https://dev1-ag-bie.oztaxa.com/species/https://id.biodiversity.org.au/taxon/algae/20215612#names)
1. [x] What happens to an identifier if it has changed at source by GBIF, CoL or NSL (NSL is special case)

#### Bring in CoL 3m

1. [x] Show CoL sample data for `Mollusca` genus `Eobania`
1. [x] ~~How are Identifiers merged / retained?~~

### Managed taxa changes: 25m

1. [x] Quick look at services features and mapper Ids
    - [Acacia Mill.](https://biodiversity.org.au/nsl/services/rest/name/apni/56859) Multiple historical IDs still mapped to the taxon
    - Treeview subtaxa example [Rhodophyta](https://id.biodiversity.org.au/tree/20220301/20205141)
1. [x] Create a name - and its dependants
1. [x] Add new taxon to the tree and bring it into TRS *(Optionally)*
    - Add instance `Xanthidium inchoatum Nordst.` to tree. Push to TRS
    - Add instance `Xanthidium acanthophorum Nordst.` as tax. synonym and push to TRS
    - Find instances with synonymy or change synonymy
1. [x] Check Tree Reports
1. [x] Publish the Tree
1. [x] Bring new name into TRS
1. [x] Difference between NSL source and NAQS source (synonym search)
1. [x] Some Synonym Examples
    - [Ectocarpus siliculosus (Dillwyn) Lyngb.](https://test-id.biodiversity.org.au/name/algae/20008190/api/apni-format)
    - [Conferva siliculosa Dillwyn](https://test-id.biodiversity.org.au/name/algae/20010417/api/apni-format)
1. [x] Everything is configurable and has small development cycle
2. [x] *Future State of NSL* - **5m**

### Extras (Time permits)

1. [x] Web Service and Web Service Documentation for TRS
1. [x] Tree Diff Reports in NSL
